"""Chat service — primary use-case orchestrator.

Coordinates prompt assembly, model inference, and conversation tracking.
"""

from uuid import UUID, uuid4

from app.config.settings import Settings
from app.core.exceptions import ModelInferenceError
from app.memory.conversation import InMemoryStore
from app.memory.context_manager import ContextManager
from app.models.base import GenerationConfig
from app.models.model_manager import ModelManager
from app.prompts.anti_sycophancy import ConversationPrompt
from app.schemas.chat import ChatRequest, ChatResponse
from app.logging.setup import get_logger

logger = get_logger(__name__)


class ChatService:
    """Handles the end-to-end chat flow for a single conversation."""

    def __init__(
        self,
        model_manager: ModelManager,
        settings: Settings,
    ) -> None:
        self._model_manager = model_manager
        self._settings = settings
        self._memory = InMemoryStore()
        self._context = ContextManager(
            self._memory,
            max_turns=settings.max_context_turns,
        )
        self._prompt = ConversationPrompt()

    async def _append_user_message_if_new(
        self,
        conversation_id: UUID,
        message: str,
    ) -> None:
        """Append the user turn unless it is already the latest message (stream retry)."""
        history = await self._memory.get_history(conversation_id)
        if history and history[-1]["role"] == "user" and history[-1]["content"] == message:
            return
        await self._memory.append(conversation_id, "user", message)

    async def process_message(self, request: ChatRequest) -> ChatResponse:
        """Process a user message and return the model's response."""
        conversation_id = request.conversation_id or uuid4()

        await self._append_user_message_if_new(conversation_id, request.message)
        history = await self._context.build_context(conversation_id)

        messages = self._prompt.to_chat_format(
            user_message=request.message,
            history=history[:-1] if history else None,
        )

        if not self._model_manager.is_loaded:
            await self._model_manager.load()

        config = GenerationConfig(
            max_tokens=self._settings.max_tokens,
            temperature=self._settings.temperature,
            top_p=self._settings.top_p,
        )

        try:
            reply = await self._model_manager.generate(messages, config)
        except ModelInferenceError:
            raise
        except Exception as exc:
            raise ModelInferenceError(str(exc)) from exc

        await self._memory.append(conversation_id, "assistant", reply)

        model_name = self._model_manager.info.model_id if self._model_manager.info else None
        logger.info("Chat completed for conversation %s", conversation_id)

        return ChatResponse(
            conversation_id=conversation_id,
            message=reply,
            model=model_name,
        )

    async def stream_message(self, request: ChatRequest):
        """Yield tokens as they are generated by the model."""
        conversation_id = request.conversation_id or uuid4()

        await self._append_user_message_if_new(conversation_id, request.message)
        history = await self._context.build_context(conversation_id)

        messages = self._prompt.to_chat_format(
            user_message=request.message,
            history=history[:-1] if history else None,
        )

        if not self._model_manager.is_loaded:
            await self._model_manager.load()

        config = GenerationConfig(
            max_tokens=self._settings.max_tokens,
            temperature=self._settings.temperature,
            top_p=self._settings.top_p,
        )

        full_reply: list[str] = []
        try:
            async for token in self._model_manager.generate_stream(messages, config):
                full_reply.append(token)
                yield conversation_id, token, False
        except Exception as exc:
            raise ModelInferenceError(str(exc)) from exc

        complete = "".join(full_reply)
        await self._memory.append(conversation_id, "assistant", complete)
        yield conversation_id, "", True

    async def get_conversation_history(self, conversation_id: UUID) -> list[dict]:
        """Retrieve prior messages for context window assembly."""
        return await self._memory.get_history(conversation_id)
